### ISSUE TITLE
Link shinyapps.io

### ISSUE THREAD

**Issue by aephidayatuloh** [adelia-putri-pangestika/rshiny#1]
Boleh ditambahkan link shinyapps.io dari aplikasi ini agar saya bisa akses secara online?

Terima kasih dan salam,
Aep

**Comment by adelia-putri-pangestika** [comment]
Berikut link nya pak

https://adeliaa.shinyapps.io/Ex-design/

Terima kasih

Pada tanggal Sen, 3 Okt 2022 pukul 20.44 Aep Hidyatuloh <
***@***.***> menulis:

**Comment by aephidayatuloh** [comment]
Link nya disertakan juga di bagian README ya

Terima kasih
